parameters:
  config.files:
    - "services.yml"
    - "serializers.yml"
    - "cron.yml"
    - "plugin-info.yml"
    - "logger.yml"
    - "field-processor.yml"
    - "migrations.yml"
    - "installable.yml"
    - "register-on-startup.yml"
