parameters:
  # Property mapper general definitions
  # all not listed here should be sent for translation
  field.processor.default:
    ignore: # do not clone
      - '_edit_lock'
      - '_edit_last'
      - '_yoast_wpseo_canonical'
      - '_yoast_wpseo_redirect'
      - 'post_date'
      - 'post_date_gmt'
      - 'post_modified'
      - 'post_modified_gmt'
      - 'guid'
      - 'comment_count'
      - 'post_name'
      - 'post_parent'
      - 'hash'
      - 'ID'
      - 'id'
      - 'term_id'
      - 'slug'
      - 'term_group'
      - 'term_taxonomy_id'
      - 'parent'
      - '_menu_item_object_id'
      - 'smartlingId'
      - 'attachment_id'
      - 'testimonial_id'
      - 'testimonials'
    key: # add jey to XML
      seo: # key="seo"
        - '_yoast_wpseo_title'
        - '_yoast_wpseo_bctitle'
        - '_yoast_wpseo_metadesc'
        - '_yoast_wpseo_metakeywords'
        - '_yoast_wpseo_focuskw'
        - '_yoast_wpseo_opengraph-description'
        - '_yoast_wpseo_google-plus-description'
    copy: # do not trandlate, but clone
      name: # by full name
        - '_yoast_wpseo_meta-robots-noindex'
        - '_yoast_wpseo_meta-robots-nofollow'
        - '_yoast_wpseo_meta-robots-adv'
        - 'post_status'
        - 'comment_status'
        - 'ping_status'
        - 'post_password'
        - 'to_ping'
        - 'pinged'
        - 'post_content_filtered'
        - 'post_type'
        - 'post_mime_type'
        - 'post_author'
        - 'taxonomy'
        - 'background'
        - 'effective_date'
        - 'icon'
        - 'menu_order'
        - 'sm_body_class'
        - '_wp_page_template'
        - 'ccb_curated_page'
        - 'sm_left_sidebar'
        - 'sm_hide_sidebar'
        - 'header_template_meta_box'
        - 'header_nav_visibility_meta_box'
        - 'header_sign_in_visibility_meta_box'
        - 'header_help_visibility_meta_box'
        - 'footer_template_meta_box'
        - 'footer_main_menu_visibility_meta_box'
        - 'language_menu_visibility_meta_box'
        - 'short_menu_visibility_meta_box'
        - '_call_to_action'
        - 'call_to_action'
        - '_dh_display_featured_image'
        - 'sm_dh_sidebar_order'
        - 'sm_dh_text_cta_link'
        - 'sm_dh_footer_cta_link_yellow'
        - 'sm_dh_cta_type'
        - 'sm_dh_sidebar_cta_type'
        - 'sm_dh_footer_cta_link_gray'
        - 'sm_dh_sidebar_cta_sv_link_yellow'
        - 'sm_dh_sidebar_cta_sv_link_gray'
        - '_yoast_wpseo_opengraph-image'
        - 'sm_dh_sidebar_reach_link'
        - 'sm_dh_sidebar_audience_link'
        - '_marketo_sidebar'
        - '_post_restored_from'
        - 'sm_dh_button_cta_link'
        - 'sm_dh_sidebar_cta_au_link_yellow'
        - '_menu_item_object'
        - '_menu_item_classes'
        - '_menu_item_type'
        - '_wp_attached_file'
        - 'file'
        ### Widget fields
        - 'bar'
        - 'widgetType'
        - 'count'
        - 'dropdown'
        - 'hierarchical'
        - 'sortby'
        - 'exclude'
        - 'number'
        - 'filter'
        - 'taxonomy'
        - 'show_date'
        - 'url'
        - 'items'
        - 'show_summary'
        - 'show_author'
        - 'show_date'
      regexp: # by value match
       - '^\d+([,\.]\d+)?$'
       - '^(y|yes|n|no|on|off|default|in|out|html|cta\d+|cta|any|null|text|surveys|choose|button)$'
       - '^(http:|https:|field_)'
       - '^(callout|card-list|card-icon-list|cta|cta-hero|cta-sidebar|image-text-list|list-icon|list|nav|template-list|embeds|html|basic|select|gold|platinum)$' # SM CuratedPage markers
       - '^(taxonomy|category|\s+)$'
       - '^(true|false|enabled|disabled|background-image)$'
