services:
  migration.150512:
    class:	Smartling\DbAl\Migrations\Migration150512

  migration.150619:
    class:	Smartling\DbAl\Migrations\Migration150619

  migration.151222:
    class: Smartling\DbAl\Migrations\Migration151222

  migration.160125:
    class: Smartling\DbAl\Migrations\Migration160125

  migration.160222:
    class: Smartling\DbAl\Migrations\Migration160222

  migration.160223:
    class: Smartling\DbAl\Migrations\Migration160223

  migration.160411:
    class: Smartling\DbAl\Migrations\Migration160411

  manager.db.migrations:
    class: Smartling\DbAl\Migrations\DbMigrationManager
    arguments:
      - "@logger"
    calls:
      - [ "registerMigration", [ "@migration.150512" ]]
      - [ "registerMigration", [ "@migration.150619" ]]
      - [ "registerMigration", [ "@migration.151222" ]]
      - [ "registerMigration", [ "@migration.160125" ]]
      - [ "registerMigration", [ "@migration.160222" ]]
      - [ "registerMigration", [ "@migration.160223" ]]
      - [ "registerMigration", [ "@migration.160411" ]]
