parameters:
  cron.interval.fiveminutes: 5m

services:
  cron.worker.upload:
    class: Smartling\Jobs\UploadJob
    arguments:
      - "@logger"
      - "@manager.submission"
    calls:
      - [ "setJobRunInterval", [ %cron.interval.fiveminutes% ] ]

  manager.register:
    class: Smartling\StartupRegisterManager
    calls:
      - [ "addService", [ @cron.worker.upload ]]
      - [ "addService", [ @wp.i18n]]
      - [ "addService", [ @wp.checkStatus]]
      - [ "addService", [ @wp.submissions]]
      - [ "addService", [ @wp.bulkSubmit]]
      - [ "addService", [ @wp.settings]]
      - [ "addService", [ @wp.settings.edit]]
      - [ "addService", [ @wp.post]]
      - [ "addService", [ @wp.page]]
      - [ "addService", [ @wp.taxonomy]]
      - [ "addService", [ @wp.ext.policy]]
      - [ "addService", [ @wp.ext.partner]]
      - [ "addService", [ @wp.ext.testimonial]]
      - [ "addService", [ @smartling.helper.relative-image-path-support]]