parameters:
  multilang_plugins:
    "multilingual-press-pro": false

  submission.pagesize: 10

services:

  smartling.helper.relative-image-path-support:
    class: Smartling\Helpers\RelativeLinkedAttachmentCoreHelper
    arguments:
      - "@logger"
      - "@entrypoint"

  helper.customMenu:
    class: Smartling\Helpers\CustomMenuContentTypeHelper
    calls:
      - [ "setSiteHelper", [ "@site.helper" ] ]
      - [ "setContentIoFactory", [ "@factory.contentIO" ] ]

  wrapper.sdk.api.smartling:
    class: Smartling\ApiWrapper
    arguments:
      - "@manager.settings"
      - "@logger"
      - "%plugin.name%"
      - "%plugin.version%"

  entrypoint:
    class: Smartling\Base\SmartlingCore
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setSubmissionManager", [ "@manager.submission" ]]
      - [ "setSettings", [ "@manager.settings" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]
      - [ "setApiWrapper", [ "@wrapper.sdk.api.smartling" ]]
      - [ "setMultilangProxy", [ "@multilang.proxy" ]]
      - [ "setContentIoFactory", [ "@factory.contentIO" ]]
      - [ "setCache", [ "@site.cache" ]]
      - [ "setCustomMenuHelper", [ "@helper.customMenu" ]]
      - [ "setSettingsManager", [ "@manager.settings" ]]

  wrapper.widget:
    class: Smartling\DbAl\WordpressContentEntities\WidgetEntity
    arguments:
      - "@logger"

  wrapper.entity.menu:
    class: Smartling\DbAl\WordpressContentEntities\MenuEntity
    arguments:
      - "@logger"

  wrapper.entity.menuitem:
      class: Smartling\DbAl\WordpressContentEntities\MenuItemEntity
      arguments:
        - "@logger"

  wrapper.entity.post:
    class: Smartling\DbAl\WordpressContentEntities\PostEntity
    arguments:
      - "@logger"

  wrapper.entity.ext.partner:
    class: Smartling\DbAl\WordpressContentEntities\PartnerEntity
    arguments:
      - "@logger"

  wrapper.entity.ext.testimonial:
    class: Smartling\DbAl\WordpressContentEntities\TestimonialEntity
    arguments:
      - "@logger"

  wrapper.entity.ext.policy:
    class: Smartling\DbAl\WordpressContentEntities\PolicyEntity
    arguments:
      - "@logger"

  wrapper.entity.page:
    class: Smartling\DbAl\WordpressContentEntities\PageEntity
    arguments:
      - "@logger"

  wrapper.entity.category:
    class: Smartling\DbAl\WordpressContentEntities\CategoryEntity
    arguments:
      - "@logger"

  wrapper.entity.tag:
    class: Smartling\DbAl\WordpressContentEntities\TagEntity
    arguments:
      - "@logger"

  wrapper.entity.attachment:
      class: Smartling\DbAl\WordpressContentEntities\AttachmentEntity
      arguments:
        - "@logger"

  factory.contentIO:
    class: Smartling\Processors\ContentEntitiesIOFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerHandler", ["post", "@wrapper.entity.post"]]
      - [ "registerHandler", ["nav_menu", "@wrapper.entity.menu"]]
      - [ "registerHandler", ["nav_menu_item", "@wrapper.entity.menuitem"]]
      - [ "registerHandler", ["page", "@wrapper.entity.page"]]
      - [ "registerHandler", ["category", "@wrapper.entity.category"]]
      - [ "registerHandler", ["post_tag", "@wrapper.entity.tag"]]
      - [ "registerHandler", ["policy", "@wrapper.entity.ext.policy"]]
      - [ "registerHandler", ["partner", "@wrapper.entity.ext.partner"]]
      - [ "registerHandler", ["testimonial", "@wrapper.entity.ext.testimonial"]]
      - [ "registerHandler", ["theme_widget", "@wrapper.widget"]]
      - [ "registerHandler", ["attachment", "@wrapper.entity.attachment"]]

  fileLoggerLineFormatter:
    #class: Monolog\Formatter\LineFormatter
    class: Smartling\Base\CustomLogLineFormatter
    arguments:
      - "%logger.formatter.output.short_with_request_id%"
      - "%logger.formatter.date%"
      - "%logger.formatter.allow_multiline%"

  fileLoggerHandlerStandard:
    class: Monolog\Handler\StreamHandler
    arguments:
      - "%logger.filehandler.standard.filename%"
      - "%logger.filehandler.standard.loglevel%"
    calls:
      - [ "setFormatter", [ "@fileLoggerLineFormatter" ]]

  fileLoggerHandlerRotatable:
     class: Monolog\Handler\RotatingFileHandler
     arguments:
       - "%logger.filehandler.standard.filename%"
       - "%logger.filehandler.standard.maxfiles%"
       - "%logger.filehandler.standard.loglevel%"
     calls:
       - [ "setFormatter", [ "@fileLoggerLineFormatter" ]]

  logger:
    class: Monolog\Logger
    arguments:
      - "%logger.channel%"
    calls:
      - [pushHandler, ["@fileLoggerHandlerRotatable"]]

  manager.submission:
    class: Smartling\Submissions\SubmissionManager
    arguments:
     - "@logger"
     - "@site.db"
     - "%submission.pagesize%"
     - "@entity.helper"

  site.helper:
    class: Smartling\Helpers\SiteHelper
    arguments:
      - "@logger"

  site.db:
    class: Smartling\DbAl\DB
    arguments:
      - "@logger"
      - "%logger.smartling_log_raw_sql%"

  site.cache:
    class: Smartling\Helpers\Cache

  manager.settings:
    class: Smartling\Settings\SettingsManager
    arguments:
      - "@logger"
      - "@site.db"
      - "%submission.pagesize%"
      - "@site.helper"
      - "@multilang.proxy"

  plugin.info:
      class: Smartling\Helpers\PluginInfo
      arguments:
        - "%plugin.name%"
        - "%plugin.version%"
        - "%plugin.url%"
        - "%plugin.dir%"
        - "%plugin.domain%"
        - "@manager.settings"
        - "%plugin.upload%"

  multilang.proxy:
    class: Smartling\DbAl\MultiligualPressConnector
    arguments:
      - "@logger"
      - "@site.helper"
      - "%multilang_plugins%"

  entity.helper:
    class: Smartling\Helpers\EntityHelper
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setPluginInfo", [ "@plugin.info" ]]
      - [ "setConnector", [ "@multilang.proxy" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]

  wp.cron:
    class: Smartling\WP\JobEngine
    arguments:
      - "@logger"
      - "@plugin.info"

  wp.i18n:
    class: Smartling\WP\i18n
    arguments:
      - "@plugin.info"

  wp.settings:
    class: Smartling\WP\Controller\ConfigurationProfilesController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.settings.edit:
    class: Smartling\WP\Controller\ConfigurationProfileFormController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.submissions:
    class: Smartling\WP\Controller\SubmissionsPageController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.post:
    class: Smartling\WP\Controller\PostWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.partner:
    class: Smartling\WP\Controller\PartnerWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.testimonial:
    class: Smartling\WP\Controller\TestimonialWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.policy:
    class: Smartling\WP\Controller\PolicyWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.page:
    class: Smartling\WP\Controller\PageWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.taxonomy:
      class: Smartling\WP\Controller\TaxonomyWidgetController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.checkStatus:
      class: Smartling\WP\Controller\CheckStatusController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.bulkSubmit:
    class: Smartling\WP\Controller\BulkSubmitController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"


  extension.translation_lock:
    class: Smartling\Extensions\TranslateLock

  extension.loader:
    class: Smartling\Extensions\ExtensionLoader
    arguments:
      - "@logger"
    calls:
      - [ "registerExtension", [ "@extension.translation_lock" ]]

  migration.150512:
    class:	Smartling\DbAl\Migrations\Migration150512

  migration.150619:
    class:	Smartling\DbAl\Migrations\Migration150619

  migration.151222:
    class: Smartling\DbAl\Migrations\Migration151222

  migration.160125:
    class: Smartling\DbAl\Migrations\Migration160125


  manager.db.migrations:
    class: Smartling\DbAl\Migrations\DbMigrationManager
    arguments:
      - "@logger"
    calls:
      - [ "registerMigration", [ "@migration.150512" ]]
      - [ "registerMigration", [ "@migration.150619" ]]
      - [ "registerMigration", [ "@migration.151222" ]]
      - [ "registerMigration", [ "@migration.160125" ]]
