parameters:

  multilang_plugins:
    "multilingual-press-pro": false
    "polylang": false

  plugin.name: smartling-connector
  plugin.version: 1.0.10-dev
  plugin.domain: smartling-connector
  wp.hooks: ['wp.cron', 'wp.i18n', 'wp.checkStatus', 'wp.submissions', 'wp.bulkSubmit', 'wp.settings', 'wp.post', 'wp.page', 'wp.taxonomy']

  logger.channel: default
  logger.filehandler.standard.filename: %plugin.dir%/logfile
  logger.filehandler.standard.loglevel: DEBUG
  logger.filehandler.standard.maxfiles: 5

  submission.pagesize: 5


services:

  wrapper.sdk.api.smartling:
    class: Smartling\ApiWrapper
    arguments:
    - "@manager.settings"
    - "@logger"

  entrypoint:
    class: Smartling\Base\SmartlingCore
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setSubmissionManager", [ "@manager.submission" ]]
      - [ "setSettings", [ "@manager.settings" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]
      - [ "setApiWrapper", [ "@wrapper.sdk.api.smartling" ]]
      - [ "setMultilangProxy", [ "@multilang.proxy" ]]
      - [ "setContentIoFactory", [ "@factory.contentIO" ]]

  wrapper.entity.post:
    class: Smartling\DbAl\WordpressContentEntities\PostEntity
    arguments:
      - "@logger"

  wrapper.entity.page:
    class: Smartling\DbAl\WordpressContentEntities\PageEntity
    arguments:
      - "@logger"

  wrapper.entity.category:
    class: Smartling\DbAl\WordpressContentEntities\CategoryEntity
    arguments:
      - "@logger"

  wrapper.entity.tag:
    class: Smartling\DbAl\WordpressContentEntities\TagEntity
    arguments:
      - "@logger"

  mapper.post:
    class: Smartling\Processors\PostMapper

  mapper.page:
    class: Smartling\Processors\PageMapper

  mapper.category:
    class: Smartling\Processors\CategoryMapper

  mapper.tag:
    class: Smartling\Processors\TagMapper

  factory.propertyMapper:
    class: Smartling\Processors\PropertyMapperFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerMapper", ["post", "@mapper.post"]]
      - [ "registerMapper", ["page", "@mapper.page"]]
      - [ "registerMapper", ["category", "@mapper.category"]]
      - [ "registerMapper", ["post_tag", "@mapper.tag"]]


  factory.contentIO:
    class: Smartling\Processors\ContentEntitiesIOFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerMapper", ["post", "@wrapper.entity.post"]]
      - [ "registerMapper", ["page", "@wrapper.entity.page"]]
      - [ "registerMapper", ["category", "@wrapper.entity.category"]]
      - [ "registerMapper", ["post_tag", "@wrapper.entity.tag"]]

  fileLoggerHandlerStandard:
    class: Monolog\Handler\StreamHandler
    arguments:
      - "%logger.filehandler.standard.filename%"
      - "%logger.filehandler.standard.loglevel%"

  fileLoggerHandlerRotatable:
     class: Monolog\Handler\RotatingFileHandler
     arguments:
       - "%logger.filehandler.standard.filename%"
       - "%logger.filehandler.standard.maxfiles%"
       - "%logger.filehandler.standard.loglevel%"

  logger:
    class: Monolog\Logger
    arguments:
      - "%logger.channel%"
    calls:
      - [pushHandler, ["@fileLoggerHandlerRotatable"]]

  manager.submission:
    class: Smartling\Submissions\SubmissionManager
    arguments:
     - "@logger"
     - "@site.db"
     - "%submission.pagesize%"
     - "@entity.helper"

  site.helper:
    class: Smartling\Helpers\SiteHelper
    arguments:
      - "@logger"

  site.db:
    class: Smartling\DbAl\DB
    arguments:
      - "@logger"

  site.cache:
    class: Smartling\Helpers\Cache

  manager.settings:
    class: Smartling\Settings\SettingsManager
    arguments:
      - "@logger"
      - "@factory.propertyMapper"
      - "@site.helper"
      - "@multilang.proxy"

  plugin.info:
      class: Smartling\Helpers\PluginInfo
      arguments:
        - "%plugin.name%"
        - "%plugin.version%"
        - "%plugin.url%"
        - "%plugin.dir%"
        - "%plugin.domain%"
        - "@manager.settings"
        - "%plugin.upload%"

  multilang.proxy:
    class: Smartling\DbAl\MultiligualPressConnector
    arguments:
      - "@logger"
      - "@site.helper"
      - "%multilang_plugins%"

  entity.helper:
    class: Smartling\Helpers\EntityHelper
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setPluginInfo", [ "@plugin.info" ]]
      - [ "setConnector", [ "@multilang.proxy" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]

  wp.cron:
    class: Smartling\WP\JobEngine
    arguments:
      - "@logger"
      - "@plugin.info"

  wp.i18n:
    class: Smartling\WP\i18n
    arguments:
      - "@plugin.info"

  wp.settings:
    class: Smartling\WP\Controller\SettingsController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.submissions:
    class: Smartling\WP\Controller\SubmissionsPageController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.post:
    class: Smartling\WP\Controller\PostWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.page:
    class: Smartling\WP\Controller\PageWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.taxonomy:
      class: Smartling\WP\Controller\TaxonomyWidgetController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.checkStatus:
      class: Smartling\WP\Controller\CheckStatusController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.bulkSubmit:
    class: Smartling\WP\Controller\BulkSubmitController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"