parameters:
  plugin.name: smartling-connector
  plugin.version: 1.0
  plugin.domain: smartling-connector
  wp.hooks: ['wp.i18n', 'wp.submissions', 'wp.settings', 'wp.post', 'wp.taxonomy']

  logger.channel: default
  logger.filehandler.standard.filename: %plugin.dir%/logfile.log
  logger.filehandler.standard.loglevel: DEBUG

  submission.pagesize: 5

services:

  fileLoggerHandlerStandard:
    class: Monolog\Handler\StreamHandler
    arguments:
      - "%logger.filehandler.standard.filename%"
      - "%logger.filehandler.standard.loglevel%"


  logger:
    class: Monolog\Logger
    arguments:
      - "%logger.channel%"
    calls:
      - [pushHandler, ["@fileLoggerHandlerStandard"]]

  manager.submission:
    class: Smartling\Submissions\SubmissionManager
    arguments:
     - "@logger"
     - "@site.db"
     - "%submission.pagesize%"
     - "@entity.helper"

  site.helper:
    class: Smartling\Helpers\SiteHelper
    arguments:
      - "@logger"

  site.db:
    class: Smartling\DbAl\DB
    arguments:
      - "@logger"

  plugin.options:
      class: Smartling\Helpers\Options

  plugin.info:
      class: Smartling\Helpers\PluginInfo
      arguments:
        - %plugin.name%
        - %plugin.version%
        - %plugin.url%
        - %plugin.dir%
        - %plugin.domain%
        - '@plugin.options'
        - %plugin.upload%

  multilang.proxy:
    class: Smartling\DbAl\MultiligualPressProConnector
    arguments:
      - "@logger"
      - "@site.helper"
      - "@multilang_plugins"

  entity.helper:
    class: Smartling\Helpers\EntityHelper
    arguments:
       - "@plugin.info"
       - "@multilang.proxy"
       - "@site.helper"
       - "@logger"

  wp.i18n:
    class: Smartling\WP\i18n
    arguments:
      - "@plugin.info"

  wp.settings:
    class: Smartling\WP\Controller\SettingsController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"

  wp.submissions:
    class: Smartling\WP\Controller\SubmissionsPageController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"

  wp.post:
    class: Smartling\WP\Controller\PostWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"

  wp.taxonomy:
      class: Smartling\WP\Controller\TaxonomyWidgetController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"

