parameters:
  plugin.name: smartling-connector
  plugin.version: 1.0
  plugin.domain: smartling-connector
  wp.hooks: ['wp.i18n', 'wp.submissions', 'wp.settings', 'wp.post', 'wp.taxonomy']

  logger.channel: default
  logger.filehandler.standard.filename: %plugin.dir%/logfile.log
  logger.filehandler.standard.loglevel: DEBUG

services:

  fileLoggerHandlerStandard:
    class: Monolog\Handler\StreamHandler
    arguments:
      - "%logger.filehandler.standard.filename%"
      - "%logger.filehandler.standard.loglevel%"


  logger:
    class: Monolog\Logger
    arguments:
      - "%logger.channel%"
    calls:
      - [pushHandler, ["@fileLoggerHandlerStandard"]]

  site.helper:
    class: Smartling\Helpers\SiteHelper
    arguments:
      - "@logger"

  site.db:
    class: Smartling\DbAl\DB
    arguments:
      - "@logger"

  plugin.options:
      class: Smartling\Helpers\Options

  plugin.info:
      class: Smartling\Helpers\PluginInfo
      arguments:
        - %plugin.name%
        - %plugin.version%
        - %plugin.url%
        - %plugin.dir%
        - %plugin.domain%
        - '@plugin.options'

  multilang.proxy:
    class: Smartling\DbAl\MultiligualPressProConnector
    arguments:
      - "@logger"
      - "@site.helper"
      - "@multilang_plugins"
  wp.i18n:
    class: Smartling\WP\i18n
    arguments:
      - "@plugin.info"

  wp.settings:
    class: Smartling\WP\Settings
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"

  wp.submissions:
    class: Smartling\WP\Submissions
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"

  wp.post:
    class: Smartling\WP\PostWidget
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"

  wp.taxonomy:
      class: Smartling\WP\TaxonomyWidget
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"