parameters:
  multilang_plugins:
    "multilingual-press-pro": false
    "polylang": false

  plugin.name: smartling-connector
  plugin.version: 1.0.16@2015-06-04
  plugin.domain: smartling-connector
  wp.hooks:
    - 'wp.cron'
    - 'wp.i18n'
    - 'wp.checkStatus'
    - 'wp.submissions'
    - 'wp.bulkSubmit'
    - 'wp.settings'
    - 'wp.settings.edit'
    - 'wp.post'
    - 'wp.page'
    - 'wp.taxonomy'
    - 'wp.ext.policy'
    - 'wp.ext.partner'
    - 'wp.ext.testimonial'

  logger.channel: default
  logger.filehandler.standard.filename: %plugin.dir%/logs/logfile
  logger.filehandler.standard.loglevel: DEBUG
  logger.filehandler.standard.maxfiles: 5

  logger.formatter.date: "Y-m-d H:i:s"
  logger.formatter.output.default: "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
  logger.formatter.output.short: "[%%datetime%%] %%level_name%%: %%message%%\n"

  submission.pagesize: 10

services:
  processor.property.default:
    class: Smartling\Processors\PropertyProcessors\PropertyProcessorDefault
    arguments:
      - "@logger"

  processor.property.yoast-seo:
    class: Smartling\Processors\PropertyProcessors\PropertyProcessorYoast
    arguments:
      - "@logger"

  processor.property.serialized.array:
    class: Smartling\Processors\PropertyProcessors\PropertyProcessorSerializedArray
    arguments:
      - "@logger"


  factory.processor:
    class: Smartling\Processors\PropertyProcessors\PropertyProcessorFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerDefaultProcessor", [ "@processor.property.default" ]]
      - [ "registerProcessor", [ "@processor.property.yoast-seo" ]]
      - [ "registerProcessor", [ "@processor.property.serialized.array" ]]


  wrapper.sdk.api.smartling:
    class: Smartling\ApiWrapper
    arguments:
      - "@manager.settings"
      - "@logger"

  entrypoint:
    class: Smartling\Base\SmartlingCore
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setSubmissionManager", [ "@manager.submission" ]]
      - [ "setSettings", [ "@manager.settings" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]
      - [ "setApiWrapper", [ "@wrapper.sdk.api.smartling" ]]
      - [ "setMultilangProxy", [ "@multilang.proxy" ]]
      - [ "setContentIoFactory", [ "@factory.contentIO" ]]
      - [ "setProcessorFactory", [ "@factory.processor" ]]

  wrapper.entity.post:
    class: Smartling\DbAl\WordpressContentEntities\PostEntity
    arguments:
      - "@logger"

  wrapper.entity.ext.partner:
    class: Smartling\DbAl\WordpressContentEntities\PartnerEntity
    arguments:
      - "@logger"
  wrapper.entity.ext.testimonial:
    class: Smartling\DbAl\WordpressContentEntities\TestimonialEntity
    arguments:
      - "@logger"

  wrapper.entity.ext.policy:
    class: Smartling\DbAl\WordpressContentEntities\PolicyEntity
    arguments:
      - "@logger"

  wrapper.entity.page:
    class: Smartling\DbAl\WordpressContentEntities\PageEntity
    arguments:
      - "@logger"

  wrapper.entity.category:
    class: Smartling\DbAl\WordpressContentEntities\CategoryEntity
    arguments:
      - "@logger"

  wrapper.entity.tag:
    class: Smartling\DbAl\WordpressContentEntities\TagEntity
    arguments:
      - "@logger"

  mapper.post:
    class: Smartling\Processors\ContentTypeMapper\PostMapper

  mapper.ext.policy:
    class: Smartling\Processors\ContentTypeMapper\PolicyMapper

  mapper.ext.testimonial:
    class: Smartling\Processors\ContentTypeMapper\TestimonialMapper

  mapper.ext.partner:
    class: Smartling\Processors\ContentTypeMapper\PartnerMapper

  mapper.page:
    class: Smartling\Processors\ContentTypeMapper\PageMapper

  mapper.category:
    class: Smartling\Processors\ContentTypeMapper\CategoryMapper

  mapper.tag:
    class: Smartling\Processors\ContentTypeMapper\TagMapper

  factory.propertyMapper:
    class: Smartling\Processors\PropertyMapperFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerHandler", ["post", "@mapper.post"]]
      - [ "registerHandler", ["page", "@mapper.page"]]
      - [ "registerHandler", ["category", "@mapper.category"]]
      - [ "registerHandler", ["post_tag", "@mapper.tag"]]
      - [ "registerHandler", ["policy", "@mapper.ext.policy"]]
      - [ "registerHandler", ["partner", "@mapper.ext.partner"]]
      - [ "registerHandler", ["testimonial", "@mapper.ext.testimonial"]]


  factory.contentIO:
    class: Smartling\Processors\ContentEntitiesIOFactory
    arguments:
      - "@logger"
    calls:
      - [ "registerHandler", ["post", "@wrapper.entity.post"]]
      - [ "registerHandler", ["page", "@wrapper.entity.page"]]
      - [ "registerHandler", ["category", "@wrapper.entity.category"]]
      - [ "registerHandler", ["post_tag", "@wrapper.entity.tag"]]
      - [ "registerHandler", ["policy", "@wrapper.entity.ext.policy"]]
      - [ "registerHandler", ["partner", "@wrapper.entity.ext.partner"]]
      - [ "registerHandler", ["testimonial", "@wrapper.entity.ext.testimonial"]]

  fileLoggerLineFormatter:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "%logger.formatter.output.short%"
      - "%logger.formatter.date%"

  fileLoggerHandlerStandard:
    class: Monolog\Handler\StreamHandler
    arguments:
      - "%logger.filehandler.standard.filename%"
      - "%logger.filehandler.standard.loglevel%"
    calls:
      - [ "setFormatter", [ "@fileLoggerLineFormatter" ]]

  fileLoggerHandlerRotatable:
     class: Monolog\Handler\RotatingFileHandler
     arguments:
       - "%logger.filehandler.standard.filename%"
       - "%logger.filehandler.standard.maxfiles%"
       - "%logger.filehandler.standard.loglevel%"
     calls:
       - [ "setFormatter", [ "@fileLoggerLineFormatter" ]]

  logger:
    class: Monolog\Logger
    arguments:
      - "%logger.channel%"
    calls:
      - [pushHandler, ["@fileLoggerHandlerRotatable"]]

  manager.submission:
    class: Smartling\Submissions\SubmissionManager
    arguments:
     - "@logger"
     - "@site.db"
     - "%submission.pagesize%"
     - "@entity.helper"

  site.helper:
    class: Smartling\Helpers\SiteHelper
    arguments:
      - "@logger"

  site.db:
    class: Smartling\DbAl\DB
    arguments:
      - "@logger"

  site.cache:
    class: Smartling\Helpers\Cache

  manager.settings:
    class: Smartling\Settings\SettingsManager
    arguments:
      - "@logger"
      - "@site.db"
      - "%submission.pagesize%"
      - "@site.helper"
      - "@multilang.proxy"
    calls:
      - ["setMapper", ["@factory.propertyMapper"]]

  plugin.info:
      class: Smartling\Helpers\PluginInfo
      arguments:
        - "%plugin.name%"
        - "%plugin.version%"
        - "%plugin.url%"
        - "%plugin.dir%"
        - "%plugin.domain%"
        - "@manager.settings"
        - "%plugin.upload%"

  multilang.proxy:
    class: Smartling\DbAl\MultiligualPressConnector
    arguments:
      - "@logger"
      - "@site.helper"
      - "%multilang_plugins%"

  entity.helper:
    class: Smartling\Helpers\EntityHelper
    calls:
      - [ "setLogger", [ "@logger" ]]
      - [ "setPluginInfo", [ "@plugin.info" ]]
      - [ "setConnector", [ "@multilang.proxy" ]]
      - [ "setSiteHelper", [ "@site.helper" ]]

  wp.cron:
    class: Smartling\WP\JobEngine
    arguments:
      - "@logger"
      - "@plugin.info"

  wp.i18n:
    class: Smartling\WP\i18n
    arguments:
      - "@plugin.info"

  wp.settings:
    class: Smartling\WP\Controller\ConfigurationProfilesController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.settings.edit:
    class: Smartling\WP\Controller\ConfigurationProfileFormController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.submissions:
    class: Smartling\WP\Controller\SubmissionsPageController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.post:
    class: Smartling\WP\Controller\PostWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.partner:
    class: Smartling\WP\Controller\PartnerWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.testimonial:
    class: Smartling\WP\Controller\TestimonialWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.ext.policy:
    class: Smartling\WP\Controller\PolicyWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.page:
    class: Smartling\WP\Controller\PageWidgetController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  wp.taxonomy:
      class: Smartling\WP\Controller\TaxonomyWidgetController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.checkStatus:
      class: Smartling\WP\Controller\CheckStatusController
      arguments:
        - "@logger"
        - "@multilang.proxy"
        - "@plugin.info"
        - "@entity.helper"
        - "@manager.submission"
        - "@site.cache"

  wp.bulkSubmit:
    class: Smartling\WP\Controller\BulkSubmitController
    arguments:
      - "@logger"
      - "@multilang.proxy"
      - "@plugin.info"
      - "@entity.helper"
      - "@manager.submission"
      - "@site.cache"

  migration.150512:
    class: Smartling\DbAl\Migrations\Migration150512

  manager.db.migrations:
    class: Smartling\DbAl\Migrations\DbMigrationManager
    arguments:
      - "@logger"
    calls:
      - [ "registerMigration", [ "@migration.150512" ]]
